name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 1am
    - cron: '0 1 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://djangocentral.com/feed/"
          max_post_count: 5
